---
namespace: insolar
bases:
  - ../mainnet
  - https://github.com:insolar/adm/kustomize/generic-block-explorer/overlays/docker-for-desktop
patches:
  - block-explorer-patch.yaml
resources:
  - external-svc.yaml
images:
  - name: block-explorer
    newName: insolar/block-explorer
    newTag: latest
generatorOptions:
  disableNameSuffixHash: true
